name: Mobile UI Tests

on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  maestro_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Run Maestro Tests
        run: maestro test .github/workflows/maestro.yaml
