name: Testing and Code Analysis

on: [push, pull_request]

permissions:
  issues: write
  pull-requests: write

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v4

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '20.11'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      - name: Run Backend Tests with Coverage
        run: |
          cd backend
          mkdir -p coverage
          # Run tests with coverage and output a text summary
          npm test -- --coverage --coverageReporters=text-summary | tee coverage/coverage-summary.txt

      - name: Upload Backend Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage/lcov.info

      - name: Upload Backend Coverage Summary
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-summary
          path: backend/coverage/coverage-summary.txt

  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v4

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '22.11'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Tests with Coverage
        run: |
          cd frontend
          mkdir -p coverage
          # Run tests with coverage and output a text summary
          npm run test -- --coverage --coverageReporters=text-summary | tee coverage/coverage-summary.txt

      - name: Upload Frontend Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage/lcov.info

      - name: Upload Frontend Coverage Summary
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-summary
          path: frontend/coverage/coverage-summary.txt

  sonar_scan:
    runs-on: ubuntu-latest
    needs: [test_backend, test_frontend]
    steps:
      - name: Checkout Code with Full History
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Java (Required for SonarCloud)
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk

      - name: Install SonarQube Scanner
        run: |
          curl -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          echo "export PATH=/opt/sonar-scanner/bin:$PATH" >> $HOME/.bashrc
          source $HOME/.bashrc
          export PATH="/opt/sonar-scanner/bin:$PATH"
          sonar-scanner --version

      - name: Download Backend Coverage Report
        uses: actions/download-artifact@v4  
        with:
          name: backend-coverage
          path: backend/coverage

      - name: Download Backend Coverage Summary
        uses: actions/download-artifact@v4  
        with:
          name: backend-coverage-summary
          path: backend/coverage

      - name: Download Frontend Coverage Report
        uses: actions/download-artifact@v4  
        with:
          name: frontend-coverage
          path: frontend/coverage

      - name: Download Frontend Coverage Summary
        uses: actions/download-artifact@v4  
        with:
          name: frontend-coverage-summary
          path: frontend/coverage

      - name: Print Backend Coverage Summary
        run: cat backend/coverage/coverage-summary.txt || echo "Backend coverage summary not found"

      - name: Print Frontend Coverage Summary
        run: cat frontend/coverage/coverage-summary.txt || echo "Frontend coverage summary not found"

      - name: Run SonarCloud Analysis
        run: |
          export PATH="/opt/sonar-scanner/bin:$PATH"
          sonar-scanner \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.projectKey=Andrew-Dagher_SOEN-390 \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info || (echo "SonarCloud analysis failed" && exit 1)

      - name: Comment Coverage on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            let backendCoverage = 'Backend coverage summary not found';
            let frontendCoverage = 'Frontend coverage summary not found';
            try {
              backendCoverage = fs.readFileSync('backend/coverage/coverage-summary.txt', 'utf8');
            } catch (error) {}
            try {
              frontendCoverage = fs.readFileSync('frontend/coverage/coverage-summary.txt', 'utf8');
            } catch (error) {}
            const coverageMessage = `
            🚀 **Code Coverage Report** 🚀

            **Backend Coverage Summary:**
            \`\`\`
            ${backendCoverage}
            \`\`\`

            **Frontend Coverage Summary:**
            \`\`\`
            ${frontendCoverage}
            \`\`\`
                        `;
                        github.rest.issues.createComment({
                          issue_number: context.payload.pull_request.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          body: coverageMessage
                        });
