name: Testing

on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test_job:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: 20.11

      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      - name: Run Backend Tests
        run: |
          cd backend
          npm test

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Install CocoaPods
        run: |
          cd frontend/ios
          pod install

      - name: Download Expo Go App
        run: |
          curl -o path/to/ExpoGo.app https://expo.io/tools#client

      - name: Run Frontend Detox Tests
        run: |
          cd frontend
          npm run test:detox
