name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.11"

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci --legacy-peer-deps

      - name: Run Backend Tests
        run: |
          cd backend
          npm test

  frontend_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.11"

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install --legacy-peer-deps

      # Install adb so that the emulator runner can locate it.
      - name: Install adb
        run: |
          sudo apt-get update
          sudo apt-get install -y android-tools-adb

      # Use the android-emulator-runner action to start an emulator,
      # build the app, and run Detox tests via the provided script.
      - name: Run Detox tests on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          avd-name: test
          force-avd-creation: true
          emulator-boot-timeout: 600
          emulator-port: 5554
          emulator-options: "-no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim"
          disable-animations: true
          script: |
            cd frontend
            npx detox build --configuration android.emu
            npx detox test --configuration android.emu
