name: Testing

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      - name: Run Backend Tests
        run: |
          cd backend
          npm test

  frontend_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      # Set up Android emulator (using an action that provisions an emulator)
      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64

      - name: Build Detox App for Android
        run: |
          cd frontend
          # Ensure your detox configuration for Android (e.g. "android.emu") is correct in package.json
          detox build --configuration android.emu

      - name: Run Detox Tests for Android
        run: |
          cd frontend
          detox test --configuration android.emu
