name: Testing and Code Analysis

on:
  push:
  pull_request:

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11'
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci
      - name: Run Backend Tests with Coverage
        run: |
          cd backend
          npm test -- --coverage

  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11'
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
      - name: Run Frontend Tests with Coverage
        run: |
          cd frontend
          npm run test -- --coverage

  sonar_scan:
    runs-on: ubuntu-latest
    needs: [test_backend, test_frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        with:
          args: >
            -Dsonar.projectKey=SOEN390
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
