name: Testing

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      - name: Run Backend Tests
        run: |
          cd backend
          npm test

  
  frontend_tests:
    runs-on: macos-latest  # iOS simulators require macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install --legacy-peer-deps

      - name: Download Expo IPA for Detox
        working-directory: ./frontend
        run: |
          mkdir -p bin
          curl -L https://example.com/path-to/Exponent.app.zip -o bin/Exponent.app.zip
          unzip -q bin/Exponent.app.zip -d bin/
          
      - name: Start Expo server
        working-directory: ./frontend
        run: |
          expo start --non-interactive &
          sleep 180

      - name: Build Detox App
        working-directory: ./frontend
        run: detox build --configuration ios.sim

      - name: Run Detox Tests
        working-directory: ./frontend
        run: detox test --configuration ios.sim
