name: Testing

on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: 20.11
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci
      - name: Run Backend Tests
        run: |
          cd backend
          npm test
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
      - name: Build Frontend (Detox)
        run: |
          cd frontend
          npm run build:ios
      - name: Run Frontend Detox Tests
        run: |
          cd frontend
          npm run test:detox
