name: Testing and Code Analysis

on: 
  push:
  pull_request:

jobs:
  test_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 20.11
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci
      - name: Run Backend Tests with Coverage
        run: |
          cd backend
          npm test -- --coverage # Shows coverage in console

  test_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 22.11
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
      - name: Run Frontend Tests with Coverage
        run: |
          cd frontend
          npm run test -- --coverage # Shows coverage in console

  sonar_scan:
    runs-on: ubuntu-latest
    needs: [test_backend, test_frontend]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Start SonarQube in Docker
        run: |
          docker run -d --name sonar \
            -p 9000:9000 \
            -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true \
            sonarqube:lts
      
      - name: Wait for SonarQube to be ready
        run: |
          echo "Waiting for SonarQube to be ready..."
          until curl -s http://localhost:9000/api/system/status | grep -q "UP"; do
            sleep 5
            echo "Waiting..."
          done
          echo "SonarQube is up and running!"

      - name: Run SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=SOEN390
            -Dsonar.sources=.
            -Dsonar.host.url=http://localhost:9000
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Report Link
        run: echo "Check SonarQube results at http://localhost:9000/dashboard?id=SOEN390"
