name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.11"

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      - name: Run Backend Tests
        run: |
          cd backend
          npm test


          frontend_tests:
            runs-on: ubuntu-latest

            steps:
              - name: Checkout repository
                uses: actions/checkout@v2

              - name: Setup Node.js
                uses: actions/setup-node@v3
                with:
                  node-version: '20.11'

              - name: Install Frontend Dependencies
                working-directory: ./frontend
                run: npm install

              # Start an Android emulator using the reactivecircus action.
              - name: Start Android Emulator
                uses: reactivecircus/android-emulator-runner@v2
                with:
                  api-level: 31
                  target: google_apis
                  arch: x86_64

              # Build your app for Android. Ensure your Detox configuration (in package.json)
              # has an "android.emu" configuration.
              - name: Build Detox App for Android
                working-directory: ./frontend
                run: detox build --configuration android.emu

              # Run Detox tests using the Android emulator.
              - name: Run Detox Tests for Android
                working-directory: ./frontend
                run: detox test --configuration android.emu
