name: Testing and Code Analysis

on: [push, pull_request]

permissions:
  issues: write
  pull-requests: write

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v4

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '20.11'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      - name: Run Backend Tests with Coverage and Save Summary
        run: |
          cd backend
          npm test -- --coverage | tee coverage_summary.txt

      - name: Upload Backend Coverage Summary
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-summary
          path: backend/coverage_summary.txt

      - name: Upload Backend Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: backend/coverage/lcov.info

  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v4

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '22.11'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Tests with Coverage and Save Summary
        run: |
          cd frontend
          npm run test -- --coverage | tee coverage_summary.txt

      - name: Upload Frontend Coverage Summary
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-summary
          path: frontend/coverage_summary.txt

      - name: Upload Frontend Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: frontend/coverage/lcov.info

  sonar_scan:
    runs-on: ubuntu-latest
    needs: [test_backend, test_frontend]
    steps:
      - name: Checkout Code with Full History
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Java (Required for SonarCloud)
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk

      - name: Install SonarQube Scanner
        run: |
          curl -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          echo "export PATH=/opt/sonar-scanner/bin:$PATH" >> $HOME/.bashrc
          source $HOME/.bashrc
          export PATH="/opt/sonar-scanner/bin:$PATH"
          sonar-scanner --version

      - name: Download Backend Artifacts
        uses: actions/download-artifact@v4  
        with:
          name: backend-coverage-summary
          path: backend
          
      - name: Download Frontend Artifacts
        uses: actions/download-artifact@v4  
        with:
          name: frontend-coverage-summary
          path: frontend

      - name: Download Backend Coverage Report
        uses: actions/download-artifact@v4  
        with:
          name: backend-coverage-report
          path: backend/coverage

      - name: Download Frontend Coverage Report
        uses: actions/download-artifact@v4  
        with:
          name: frontend-coverage-report
          path: frontend/coverage

      - name: Print Backend Coverage Report
        run: cat backend/coverage/lcov.info || echo "Backend coverage report not found"

      - name: Print Frontend Coverage Report
        run: cat frontend/coverage/lcov.info || echo "Frontend coverage report not found"

      - name: Get Backend Coverage Summary
        id: backend_cov
        run: |
          echo "backend_summary<<EOF" >> $GITHUB_OUTPUT
          cat backend/coverage_summary.txt
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get Frontend Coverage Summary
        id: frontend_cov
        run: |
          echo "frontend_summary<<EOF" >> $GITHUB_OUTPUT
          cat frontend/coverage_summary.txt
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run SonarCloud Analysis
        run: |
          export PATH="/opt/sonar-scanner/bin:$PATH"
          sonar-scanner \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.projectKey=Andrew-Dagher_SOEN-390 \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info || (echo "SonarCloud analysis failed" && exit 1)

      - name: Get SonarCloud Results
        run: "echo 'Check SonarCloud Report: https://sonarcloud.io/dashboard?id=Andrew-Dagher_SOEN-390&branch=${GITHUB_REF##*/}'"

      - name: Comment Coverage on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const backendSummary = `\n${{ steps.backend_cov.outputs.backend_summary }}`;
            const frontendSummary = `\n${{ steps.frontend_cov.outputs.frontend_summary }}`;
            const coverageMessage = `
            🚀 **Code Coverage Report** 🚀

            **Backend Coverage Summary:**
            ${backendSummary}

            **Frontend Coverage Summary:**
            ${frontendSummary}

            Coverage details are provided above as plain text.
                        `;
                        github.rest.issues.createComment({
                          issue_number: context.payload.pull_request.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          body: coverageMessage
                        });
